const images = {
  img_404: '/images/404.png',
  bannerHome: '/images/viber_image_2020-11-02_14-16-02.jpg',
  backgroundHome: '/images/backgroundHome.svg',
  event_detail_image: '/images/event_detail_image.svg',
  background_dark_blue: '/images/background_dark_blue.png',
  background_blue: '/images/background_blue.png',
  background_light_blue: '/images/background_light_blue.png',
  background_purple: '/images/background_purple.png',
  background_green: '/images/background_green.png',
  background_navy_blue: '/images/background_navy_blue.png',
  live_image: '/images/live_image.svg',
  unlive_image: '/images/unlive_image.svg',
  acb_logo_home: '/images/logo-acb-home.png',
  news_small_example: '/images/news_small.png',
  avatar: '/images/avatar.png',
  login_page: '/images/login_page.png',
  camera_profile: '/images/camera-profile.png',
  Logo_Login_acb: '/images/Logo_Login_acb.svg',
  banner_bxh: '/images/banner_bxh.svg',
  logo_event: '/images/logo_event.svg',
  background_circle: '/images/background_circle.svg',
  backgroundLogin: '/images/backgroundLogin.png',
  acb_logo: '/images/acb_logo.png',
  banner_default: '/images/banner_default.png',
  SODOLICHTRINH: '/images/SODOLICHTRINH.png',
  leader: '/images/leader.png',
  //icon
  icon_home: '/images/icon/icon_home.svg',
  icon_home_active: '/images/icon/icon_home_active.svg',
  icon_qr: '/images/icon/icon_qr_scan.svg',
  icon_calendar: '/images/icon/icon_calendar.png',
  icon_session: '/images/icon/icon_session.png',
  icon_speaker: '/images/icon/icon_speaker.png',
  icon_clock: '/images/icon/icon_clock.svg',
  icon_document: '/images/icon/icon_document.svg',
  icon_filter: '/images/icon/icon_filter.svg',
  icon_success: '/images/icon/icon_success.svg',
  icon_fail: '/images/icon/icon_fail.svg',
  icon_upload_file: '/images/icon/icon_upload_file.svg',
  icon_google: '/images/icon/icon_google.svg',
  icon_start: '/images/icon/icon_start.png',
  icon_dot: '/images/icon/icon_dot.png',
  icon_qr_profile: '/images/icon/icon_qr_profile.svg',
  icon_warning: '/images/icon/icon_warning.png',
  icon_start_dot: '/images/icon/icon_start_dot.png',
  icon_warning_dot: '/images/icon/icon_warning_dot.png',
  icon_news_dot: '/images/icon/icon_news_dot.png',
  icon_news: '/images/icon/icon_news.png',
  icon_livestream: '/images/icon/icon_livestream.png',
  icon_livestream_dot: '/images/icon/icon_livestream_dot.png',
  icon_arrow_back: '/images/icon/icon_arrow_back.png',
  icon_done: '/images/icon/icon_done.png',
  icon_rank1: '/images/icon/icon_rank1.svg',
  icon_rank2: '/images/icon/icon_rank2.svg',
  icon_rank3: '/images/icon/icon_rank3.svg',
  icon_slido: '/images/icon/icon_slido.svg',
  icon_profile: '/images/icon/icon_profile.svg',
  icon_home_navigation: '/images/icon/icon_home.svg',
  icon_rank_navigation: '/images/icon/icon_rank_navigation.png',
  icon_rank_active: '/images/icon/icon_rank_active.svg',
  icon_notification_active: '/images/icon/icon_notification_active.svg',
  icon_notification_navigation: '/images/icon/icon_notification_navigation.png',
  icon_profile_navigation: '/images/icon/icon_profile_navigation.png',
  icon_profile_active: '/images/icon/icon_profile_active.svg',
  icon_check: '/images/icon/icon_check.png',
  icon_survey: '/images/icon/icon_survey.svg',
  icon_heart: '/images/icon/icon_heart.svg',
  icon_heart_while: '/images/icon/icon_heart_while.png',
  icon_heart_red: '/images/icon/icon_heart_red.png',
  icon_star: '/images/icon/icon_star.svg',
  icon_gift_small: '/images/icon/gift_small.png',
  icon_gift_big: '/images/icon/gift_big.png',
  icon_send: '/images/icon/send.png',
  icon_close: '/images/icon/icon_close.svg',
  icon_check_filter: '/images/icon/icon_check_filter.svg',
  icon_no_data: '/images/icon/icon_no_data.svg',
  icon_notification_navigation_white:
    '/images/icon/icon_notification_navigation_white.png',
  icon_notification_navigation_blue:
    '/images/icon/icon_notification_navigation_blue.svg',
  icon_notification_banner: '/images/icon/icon_notification_banner.png',
  icon_notification_banner_dot: '/images/icon/icon_notification_banner_dot.png',
  icon_notification_banner_white:
    '/images/icon/icon_notification_banner_white.png',
  icon_notification_navigation_dot:
    '/images/icon/icon_notification_navigation_dot.png',
  icon_profile_ttsk: '/images/icon/icon_profile_ttsk.svg',
  icon_dot_white: '/images/icon/icon_dot_white.png',
  icon_search: '/images/icon/icon_search.svg',
  icon_location: '/images/icon/icon_location.svg',
  iconLogin: '/images/icon/iconLogin.png',
  icon_live: '/images/icon/icon_live.svg',
  icon_bookmark: '/images/icon/icon_bookmark.svg',
  icon_noti: '/images/icon/icon_noti.svg',
  icon_noti_dot: '/images/icon/icon_noti_dot.svg',
  icon_download: '/images/icon/icon_download.svg',
  icon_select_down: '/images/icon/icon_select_down.svg',
  icon_notification_loa: '/images/icon/icon_notification_loa.svg',
  icon_warning_point: '/images/icon/icon_warning_point.svg',
  icon_checked: '/images/icon/icon_checked.svg',
  icon_cancel_myagenda: '/images/icon/icon_cancel_bookmark.svg'
};
export { images };
